name: Update Blog Posts

# Set permissions at the workflow level
permissions:
  contents: write  # Allows read and write access to the repository contents

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Fetch and Update Blog Posts
        env:
          RSS_URL: https://lanfermann.dev/rss.xml
          READ_ME_PATH: README.md
        run: |
          python update_readme.py

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '📝 Update latest blog posts'
          file_pattern: README.md
